Top_Article:
  outputs:
    dev:
      account: tegna.us-east-1
      database: OPE_RAW_DATA
      password: rxXRAkheQqHVKMOsm0
      role: TEGNA_ADMIN
      schema: CONTENT_ANALYTICS.TOP_ART
      threads: 1
      type: snowflake
      user: SUKHJINDER_SINGH
      warehouse: LOAD_WH
  target: dev
