
version: 2

models:
  - name: check_article
    description: "A starter dbt model"
    columns:
      - name: ART
        description: "The primary key for this table"
        tests:
          - not_null


